### ISSUE TITLE
关于手机端无法正常显示问题

### ISSUE THREAD

**Issue by maple1217** [iamjohnnyzhuang/LoveRecord#1]
很感谢你的分享！很用心！

但是我在做的时候发现手机端无法正常显示github page，
请问有什么解决办法吗？

谢谢！

**Comment by iamjohnnyzhuang** [comment]
你好，手机端无法显示，可能是因为手机端使用了IE内核。
之前版本的JS语法部分使用了ES6 不兼容IE所以导致了手机端不能正常显示。

最新版本已经去掉了ES6语法兼容IE。
亲测Chrome/Firefox/Edge/IE
以及魅族自带的手机浏览器浏览均完美运行。

谢谢。
